ddb bascript and seed ddb code

diff --git a/backend-flask/bin/ddb/list-tables b/backend-flask/bin/ddb/list-tables
--- a/backend-flask/bin/ddb/list-tables
+++ b/backend-flask/bin/ddb/list-tables
@@ -1,7 +1,9 @@
 #! /usr/bin/bash
 
-if [ "$1" = "prod"]; then
-    ENDPOINT=URL""
+set -e # stops if its fails at any point 
+
+if [ "$1" = "prod" ]; then
+    ENDPOINT_URL""
 
 else
     ENDPOINT_URL="--endpoint-url=http://localhost:8000"
@@ -9,4 +11,4 @@ else
 fi
 
 
-aws dynamodb list-tables $ENDPOINT_URL \
+aws dynamodb list-tables $ENDPOINT_URL --query TableNames --output table
